show legend for waveform plots
slsdetectorgroup/pyctbgui pull request #137
Opened 2023-08-17 09:57 UTC by Bechir-Brahem

2023-08-17 13:33 UTC, erikfrojdh commented on pyctbgui/services/ADC.py
> +        self.mainWindow.plotAnalogWaveform.addLegend(colCount=4)
colCount=4 appears 4 times is this a coincidence or should it be a named variable?

2023-08-17 13:34 UTC, erikfrojdh reviewed
See comment, if just by coincidence I'll merge.

2023-08-17 14:16 UTC, Bechir-Brahem commented
added colCount in Defines

2023-08-18 07:34 UTC, erikfrojdh commented
Looking at your demo I think the legend is more in the way than helping. We anyway can see the colors from the settings on the left. @thattil: What is your opinion on this?

2023-08-21 10:33 UTC, thattil commented
@erikfrojdh @Bechir-Brahem I had a look at the PR and I see that all the legends show despite if they are selected or not. This is a bug from my side. Initially, only the selected waveforms and legends showed. I changed this to adding them all in the beginning and showing/hiding the selected/unselected waveforms, but I missed about the legends. 

If only the selected legends were shown, then maybe its not a bad idea to show them. Also I doubt all of them are selected everytime. By default, the number of columns for the legends is chosen as 4, but they could also be selected in a more intelligent manner depending on the number of selected waveforms. This is an idea that I can ask the users directly first to see if they prefer this or hiding all the legends.

2023-08-22 15:35 UTC, thattil requested changes
I would show selected legend by default.. and hide only if user sets it..

2023-08-23 06:54 UTC, thattil approved these changes

2023-08-23 06:54 UTC, merged